#!/bin/bash -e
ssh_user=ciuser
if [[ $# -lt 1 ]]; then
  echo "Simultaneous SSH session in tmux panes, courtesy of knife search"
  echo "Usage: knifemux [knife search expression] [ssh username]"
  exit 1
fi
session_name=knifemux-$(echo $1 | tr ':' '_')
session_name=$(echo $session_name | tr ' ' '_')

if [[ $# -eq 2 ]]; then
  ssh_user="${2}"
fi

tmux start-server
tmux new-session -d -s ${session_name}
#tmux new-session -A -d -s ${session_name}
echo "$1"
#hosts=`tsocks knife search -c ~/.chef/knife.rb -i "$1"`
hosts=`proxychains4 -q knife search -c ~/.chef/knife.rb -i "$1"`

echo "$ssh_user @ $session_name for $hosts"

for host in $hosts
do
  echo "$host"
  tmux splitw -t ${session_name} "ssh -C ${ssh_user}@${host}"
  tmux select-layout -t ${session_name} tiled
done
tmux kill-pane -t 0
tmux set-window-option -t ${session_name} synchronize-panes on
tmux select-layout -t ${session_name} tiled
tmux at -t ${session_name}
